import sys



WEB_DIRECTORY = "mtb"

from .Zho_TextImage import NODE_CLASS_MAPPINGS  as NODE_CLASS_MAPPINGS_TI
from .Zho_RGB_Image import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_RGB
from .Zho_ImageComposite import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_IC
from .Zho_AlphaChanel import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_AC
from .Zho_TextImage_frame import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_TIF


# Combine the dictionaries
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_TI, **NODE_CLASS_MAPPINGS_RGB, **NODE_CLASS_MAPPINGS_IC, **NODE_CLASS_MAPPINGS_AC, **NODE_CLASS_MAPPINGS_TIF}


__all__ = ['NODE_CLASS_MAPPINGS']
